select * from inventories
select * from inventory_alerts
select * from inventory_histories
select * from warehouses
select * from Suppliers
select * from products
select * from reels
select * from posts
select  * from users
select * from  wishlists
select * from user_behaviors
select * from  brands
select * from categories
select *  from orders
select *  from carts
select *  from  stories