/**
 * PostgreSQL Controllers Index
 * Exports all Sequelize-based controllers
 */

module.exports = {
  productController: require('./productController'),
  wishlistController: require('./wishlistController'),
  cartController: require('./cartController'),
  orderController: require('./orderController'),
  postsController: require('./postsController'),
  userController: require('./userController'),
  paymentController: require('./paymentController'),
  adminController: require('./adminController'),
  usersAdminController: require('./usersAdminController'),
  socialAdminController: require('./socialAdminController'),
  vendorController: require('./vendorController'),
  inventoryController: require('./inventoryController'),
  searchController: require('./searchController'),
  storiesController: require('./storiesController'),
  categoryController: require('./categoryController'),
  brandsController: require('./brandsController'),
  recommendationsController: require('./recommendationsController'),
  promotionsController: require('./promotionsController'),
  checkoutController: require('./checkoutController'),
  addressController: require('./addressController'),
  commentController: require('./commentController'),
  cmsController: require('./cmsController'),
  alertsController: require('./alertsController'),
  analyticsController: require('./analyticsController'),
  analyticsOverviewController: require('./analyticsOverviewController'),
  auditLogController: require('./auditLogController'),
  complianceController: require('./complianceController'),
  contentController: require('./contentController'),
  creatorsController: require('./creatorsController'),
  followController: require('./followController'),
  liveController: require('./liveController'),
  notificationsController: require('./notificationsController'),
  reelsController: require('./reelsController'),
  returnsController: require('./returnsController'),
  roleManagementController: require('./roleManagementController'),
  featureFlagController: require('./featureFlagController'),
  logisticsController: require('./logisticsController'),
  marketingController: require('./marketingController'),
  moduleManagementController: require('./moduleManagementController'),
  rewardController: require('./rewardController'),
  supportController: require('./supportController'),
  authController: require('./authController'),
  dataGovernanceController: require('./dataGovernanceController'),
  ecommerceAPIController: require('./ecommerceAPIController'),
  postLikeController: require('./postLikeController'),
  productCommentsController: require('./productCommentsController'),
  productSharesController: require('./productSharesController'),
  cmsMediaController: require('./cmsMediaController'),
  adminCategoriesController: require('./adminCategoriesController'),
  adminContentController: require('./adminContentController'),
  contentAPI: require('./contentAPI'),
  uploadController: require('./uploadController'),
  postsControllerSocial: require('./postsControllerSocial'),
  smartCollectionsController: require('./smartCollectionsController'),
  styleInspirationController: require('./styleInspirationController'),
  sendEmailController: require('./sendEmailController'),
};


